2025-10-13 18:49:52 [[31merror[39m]: [31mINSERT has more target columns than expressions[39m
Stack: error: [31mINSERT has more target columns than expressions[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 18:50:04 [[31merror[39m]: [31mClient has already been connected. You cannot reuse a client.[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 18:50:04 [[31merror[39m]: [31m[31mClient has already been connected. You cannot reuse a client.[31m[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 18:50:50 [[31merror[39m]: [31mINSERT has more target columns than expressions[39m
Stack: error: [31mINSERT has more target columns than expressions[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 18:51:16 [[31merror[39m]: [31mClient has already been connected. You cannot reuse a client.[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 18:51:16 [[31merror[39m]: [31m[31mClient has already been connected. You cannot reuse a client.[31m[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 18:52:38 [[31merror[39m]: [31mINSERT has more target columns than expressions[39m
Stack: error: [31mINSERT has more target columns than expressions[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 18:55:47 [[31merror[39m]: [31mClient has already been connected. You cannot reuse a client.[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 18:55:47 [[31merror[39m]: [31m[31mClient has already been connected. You cannot reuse a client.[31m[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 18:56:06 [[31merror[39m]: [31mduplicate key value violates unique constraint "unique_username"[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 18:56:06 [[31merror[39m]: [31m[31mduplicate key value violates unique constraint "unique_username"[31m[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 18:56:06 [[31merror[39m]: [31m[31m[31mduplicate key value violates unique constraint "unique_username"[31m[31m[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 18:56:08 [[31merror[39m]: [31mClient has already been connected. You cannot reuse a client.[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 18:56:08 [[31merror[39m]: [31m[31mClient has already been connected. You cannot reuse a client.[31m[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 18:56:10 [[31merror[39m]: [31mClient has already been connected. You cannot reuse a client.[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 18:56:10 [[31merror[39m]: [31m[31mClient has already been connected. You cannot reuse a client.[31m[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 18:57:00 [[31merror[39m]: [31mduplicate key value violates unique constraint "unique_username"[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 18:57:00 [[31merror[39m]: [31m[31mduplicate key value violates unique constraint "unique_username"[31m[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 18:57:00 [[31merror[39m]: [31m[31m[31mduplicate key value violates unique constraint "unique_username"[31m[31m[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 18:57:02 [[31merror[39m]: [31mClient has already been connected. You cannot reuse a client.[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 18:57:02 [[31merror[39m]: [31m[31mClient has already been connected. You cannot reuse a client.[31m[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 18:57:03 [[31merror[39m]: [31mClient has already been connected. You cannot reuse a client.[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 18:57:03 [[31merror[39m]: [31m[31mClient has already been connected. You cannot reuse a client.[31m[39m
Stack: Error: [31mClient has already been connected. You cannot reuse a client.[39m
    at Client._connect (/app/node_modules/pg/lib/client.js:95:19)
    at /app/node_modules/pg/lib/client.js:171:12
    at new Promise (<anonymous>)
    at Client.connect (/app/node_modules/pg/lib/client.js:170:12)
    at /app/src/controllers/user.ts:16:18
    at Generator.next (<anonymous>)
    at /app/src/controllers/user.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/controllers/user.ts:4:12)
    at registerController (/app/src/controllers/user.ts:24:12)
2025-10-13 19:12:49 [[31merror[39m]: [31mduplicate key value violates unique constraint "unique_username"[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:12:49 [[31merror[39m]: [31m[31mduplicate key value violates unique constraint "unique_username"[31m[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:12:49 [[31merror[39m]: [31m[31m[31mduplicate key value violates unique constraint "unique_username"[31m[31m[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:13:05 [[31merror[39m]: [31mduplicate key value violates unique constraint "unique_username"[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:13:05 [[31merror[39m]: [31m[31mduplicate key value violates unique constraint "unique_username"[31m[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:13:05 [[31merror[39m]: [31m[31m[31mduplicate key value violates unique constraint "unique_username"[31m[31m[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:12:53 [[31merror[39m]: [31mduplicate key value violates unique constraint "unique_username"[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:12:53 [[31merror[39m]: [31m[31mduplicate key value violates unique constraint "unique_username"[31m[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:12:53 [[31merror[39m]: [31m[31m[31mduplicate key value violates unique constraint "unique_username"[31m[31m[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:12:55 [[31merror[39m]: [31mduplicate key value violates unique constraint "unique_username"[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:12:55 [[31merror[39m]: [31m[31mduplicate key value violates unique constraint "unique_username"[31m[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:12:55 [[31merror[39m]: [31m[31m[31mduplicate key value violates unique constraint "unique_username"[31m[31m[39m
Stack: error: [31mduplicate key value violates unique constraint "unique_username"[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:28:44 [[31merror[39m]: [31moperator does not exist: character varying = integer[39m
Stack: error: [31moperator does not exist: character varying = integer[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:28:44 [[31merror[39m]: [31m[31moperator does not exist: character varying = integer[31m[39m
Stack: error: [31moperator does not exist: character varying = integer[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:29:36 [[31merror[39m]: [31moperator does not exist: character varying = integer[39m
Stack: error: [31moperator does not exist: character varying = integer[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-13 19:29:36 [[31merror[39m]: [31m[31moperator does not exist: character varying = integer[31m[39m
Stack: error: [31moperator does not exist: character varying = integer[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-14 16:04:03 [[31merror[39m]: [31musername is required sosal?[39m
2025-10-14 16:04:03 [[31merror[39m]: [31m[31musername is required sosal?[31m[39m
2025-10-14 17:34:49 [[31merror[39m]: [31mError in productCardController: Converting circular structure to JSON[39m
[31m    --> starting at object with constructor 'Socket'[39m
[31m    |     property 'parser' -> object with constructor 'HTTPParser'[39m
[31m    --- property 'socket' closes the circle[39m
Stack: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at /app/src/controllers/productCard.ts:15:24
    at Generator.next (<anonymous>)
    at fulfilled (/app/src/controllers/productCard.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-14 17:34:49 [[31merror[39m]: [31mConverting circular structure to JSON[39m
[31m    --> starting at object with constructor 'Socket'[39m
[31m    |     property 'parser' -> object with constructor 'HTTPParser'[39m
[31m    --- property 'socket' closes the circle[39m
Stack: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at /app/src/controllers/productCard.ts:15:24
    at Generator.next (<anonymous>)
    at fulfilled (/app/src/controllers/productCard.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-16 20:06:39 [[31merror[39m]: [31mSQL ERROR =>[39m
[31m                    [39m
[31m           select  [39m
[31m            pc.id,[39m
[31m            pc.description,[39m
[31m            pc.create_user_id,[39m
[31m            u.username,[39m
[31m            pc.current_price,[39m
[31m            pt."name" as product_type,[39m
[31m            pt.id as product_type_id,[39m
[31m            pc.create_date[39m
[31m            from app.product_card pc [39m
[31m            left join  ref.product_type pt  on pt.id = pc.product_type_id [39m
[31m            left join hr."user" u  on u.id = pc.create_user_id [39m
[31m            where true [39m
[31m    [39m
[31m            order by create_date  desc [39m
[31m        [39m
[31m                    [39m
2025-10-16 20:06:39 [[31merror[39m]: [31mError in productCardController: bind message supplies 1 parameters, but prepared statement "" requires 0[39m
Stack: error: bind message supplies 1 parameters, but prepared statement "" requires 0
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-16 20:06:39 [[31merror[39m]: [31mbind message supplies 1 parameters, but prepared statement "" requires 0[39m
Stack: error: bind message supplies 1 parameters, but prepared statement "" requires 0
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-16 20:08:06 [[31merror[39m]: [31mSQL ERROR =>[39m
[31m                    [39m
[31m           select  [39m
[31m            pc.id,[39m
[31m            pc.description,[39m
[31m            pc.create_user_id,[39m
[31m            u.username,[39m
[31m            pc.current_price,[39m
[31m            pt."name" as product_type,[39m
[31m            pt.id as product_type_id,[39m
[31m            pc.create_date[39m
[31m            from app.product_card pc [39m
[31m            left join  ref.product_type pt  on pt.id = pc.product_type_id [39m
[31m            left join hr."user" u  on u.id = pc.create_user_id [39m
[31m            where true [39m
[31m    [39m
[31m            order by create_date  desc [39m
[31m        [39m
[31m                    [39m
2025-10-16 20:08:06 [[31merror[39m]: [31mError in productCardController: bind message supplies 1 parameters, but prepared statement "" requires 0[39m
Stack: error: bind message supplies 1 parameters, but prepared statement "" requires 0
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-16 20:08:06 [[31merror[39m]: [31mbind message supplies 1 parameters, but prepared statement "" requires 0[39m
Stack: error: bind message supplies 1 parameters, but prepared statement "" requires 0
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-19 15:43:52 [[31merror[39m]: [31mrelation "hr.user" does not exist[39m
Stack: error: [31mrelation "hr.user" does not exist[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-19 15:43:52 [[31merror[39m]: [31m[31mrelation "hr.user" does not exist[31m[39m
Stack: error: [31mrelation "hr.user" does not exist[39m
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-19 15:49:00 [[31merror[39m]: [31mUnexpected token } in JSON at position 51[39m
Stack: SyntaxError: Unexpected token } in JSON at position 51
    at JSON.parse (<anonymous>)
    at parse (/app/node_modules/body-parser/lib/types/json.js:77:19)
    at /app/node_modules/body-parser/lib/read.js:123:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (/app/node_modules/raw-body/index.js:238:16)
    at done (/app/node_modules/raw-body/index.js:227:7)
    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:287:7)
    at IncomingMessage.emit (node:events:517:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1400:12)
2025-10-19 15:49:10 [[31merror[39m]: [31mSQL ERROR =>[39m
[31m                    [39m
[31m            INSERT INTO app.product_card [39m
[31m                (name, description, create_user_id, product_type_id, current_price)[39m
[31m            VALUES ($1, $2, $3, $4, $5)[39m
[31m            RETURNING id, name, description, product_type_id, current_price, create_date[39m
[31m        [39m
[31m                    test,,,1,50[39m
2025-10-19 15:49:10 [[31merror[39m]: [31mError in productCardController: insert or update on table "product_card" violates foreign key constraint "product_card_product_type_id_fkey"[39m
Stack: error: insert or update on table "product_card" violates foreign key constraint "product_card_product_type_id_fkey"
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-19 15:49:10 [[31merror[39m]: [31minsert or update on table "product_card" violates foreign key constraint "product_card_product_type_id_fkey"[39m
Stack: error: insert or update on table "product_card" violates foreign key constraint "product_card_product_type_id_fkey"
    at /app/node_modules/pg/lib/client.js:545:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-19 15:50:02 [[31merror[39m]: [31mUnexpected token } in JSON at position 76[39m
Stack: SyntaxError: Unexpected token } in JSON at position 76
    at JSON.parse (<anonymous>)
    at parse (/app/node_modules/body-parser/lib/types/json.js:77:19)
    at /app/node_modules/body-parser/lib/read.js:123:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (/app/node_modules/raw-body/index.js:238:16)
    at done (/app/node_modules/raw-body/index.js:227:7)
    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:287:7)
    at IncomingMessage.emit (node:events:517:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1400:12)
2025-10-19 15:50:07 [[31merror[39m]: [31mError in productCardController: Cannot read properties of undefined (reading 'emit')[39m
Stack: TypeError: Cannot read properties of undefined (reading 'emit')
    at /app/src/controllers/productCard.ts:36:12
    at Generator.next (<anonymous>)
    at fulfilled (/app/src/controllers/productCard.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-19 15:50:07 [[31merror[39m]: [31mCannot read properties of undefined (reading 'emit')[39m
Stack: TypeError: Cannot read properties of undefined (reading 'emit')
    at /app/src/controllers/productCard.ts:36:12
    at Generator.next (<anonymous>)
    at fulfilled (/app/src/controllers/productCard.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-10-19 15:50:13 [[31merror[39m]: [31mUnexpected token } in JSON at position 72[39m
Stack: SyntaxError: Unexpected token } in JSON at position 72
    at JSON.parse (<anonymous>)
    at parse (/app/node_modules/body-parser/lib/types/json.js:77:19)
    at /app/node_modules/body-parser/lib/read.js:123:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (/app/node_modules/raw-body/index.js:238:16)
    at done (/app/node_modules/raw-body/index.js:227:7)
    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:287:7)
    at IncomingMessage.emit (node:events:517:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1400:12)
2025-10-19 15:51:41 [[31merror[39m]: [31mUnexpected token } in JSON at position 72[39m
Stack: SyntaxError: Unexpected token } in JSON at position 72
    at JSON.parse (<anonymous>)
    at parse (/app/node_modules/body-parser/lib/types/json.js:77:19)
    at /app/node_modules/body-parser/lib/read.js:123:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (/app/node_modules/raw-body/index.js:238:16)
    at done (/app/node_modules/raw-body/index.js:227:7)
    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:287:7)
    at IncomingMessage.emit (node:events:517:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1400:12)
2025-10-19 15:55:28 [[31merror[39m]: [31mUnexpected token } in JSON at position 72[39m
Stack: SyntaxError: Unexpected token } in JSON at position 72
    at JSON.parse (<anonymous>)
    at parse (/app/node_modules/body-parser/lib/types/json.js:77:19)
    at /app/node_modules/body-parser/lib/read.js:123:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (/app/node_modules/raw-body/index.js:238:16)
    at done (/app/node_modules/raw-body/index.js:227:7)
    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:287:7)
    at IncomingMessage.emit (node:events:517:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1400:12)
